name: "Create Release"

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Release name "2.1.3"'
        required: true

jobs:
  run-something:
    name: Simple step
    runs-on: ubuntu-latest

    steps:
      - name: Verify that the current branch has a name that starts with 'release-'
        run: |
          CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
          if [[ "$CURRENT_BRANCH" == release-* ]]; then
            echo "Branch name starts with 'release-'."
          else
            echo "Branch name does not start with 'release-'."
            exit 1
          fi
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run code
        run: |
          pwd 
          ls -la
          echo ${{ github.event.inputs.name }}
          env
